name: llm-env
channels:
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - torchvision
  - pandas
  - python=3.12.12
  - scikit-learn
  - numpy
  - pytorch
  - tensorflow
prefix: /Users/haram/miniconda3/envs/llm-env
